### ISSUE TITLE
Rules and heuristics from explainer missing from spec

### ISSUE THREAD

**Issue by foolip** [WICG/largest-contentful-paint#21]
The [explainer](https://github.com/WICG/largest-contentful-paint/blob/master/README.md) for this spec is great, everyone should read it. There are a few things in there that seem not be captured by the spec but should be:
- The visible area of an element is clipped by the screen viewport, frame viewports, ancestor elements’ visible area
- The heuristics to identify a background-purposed image
- A text element in font-block period is invisible
- Excluding mouse move/enter/leave and pinch gesture
- Ignore removed elements

**Comment by yoavweiss** [comment]
> * The visible area of an element is clipped by the screen viewport, frame viewports, ancestor elements’ visible area

Most of those are covered by the intersectionRect passed on from ElementTiming, but frame viewports are not. Good catch!


> * Excluding mouse move/enter/leave and pinch gesture

I *think* that the reliance on [has dispatched input event](https://wicg.github.io/event-timing/#has-dispatched-input-event) covers that, but it's hard to tell. It might be better to change the explainer to outline which event *do* impact it.

> * Ignore removed elements

Covered by step 4 of [report image element timing](https://wicg.github.io/element-timing/#report-image-element-timing), which doesn't call "potentially add an LCP entry" if `exposedElement` is null, which is [what happens when it's not connected](https://wicg.github.io/element-timing/#get-an-element).

> The heuristics to identify a background-purposed image

This is indeed not specified currently. Thanks for catching it!


> * A text element in font-block period is invisible

I believe that's covered by [ElementTiming's CSS modifications](https://wicg.github.io/element-timing/#sec-modifications-CSS)

**Comment by yoavweiss** [comment]
Opened 3 different issues to track the missing bits, so closing this one

**Comment by foolip** [comment]
Thanks!
